### ISSUE TITLE
Перепроверка лабораторной 6 (JS замыкание)

### ISSUE THREAD

**Issue by akosayo** [akosayo/UPTwitter#9]
Доброго времени суток. За шестую лабораторную работу у меня стоит 4, насколько я понял,  такая оценка там стоит по той причине, что я реализовывал функционал сразу в виде классов, о чем мне и было сказано в комменте проверяющего. Однако, эта проблема была исправлена на следующий же день после получения комментария, но перепроверки не последовало. Если такая оценка там стоит до сих пор именно по вышеописанной причине, то прошу перепроверить, пожалуйста.

**Comment by ghost** [comment]
Работа была перепроверена, оценка 8.

Критерий на 9-10 был выполнен не полностью, и -1 за срок сдачи (8 апреля бы сделан первый пулл реквест)
